/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStrategyRouteImport } from './routes/api/strategy'

const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStrategyRoute = ApiStrategyRouteImport.update({
  id: '/api/strategy',
  path: '/api/strategy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/strategy': typeof StrategyRoute
  '/api/strategy': typeof ApiStrategyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/strategy': typeof StrategyRoute
  '/api/strategy': typeof ApiStrategyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/strategy': typeof StrategyRoute
  '/api/strategy': typeof ApiStrategyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/questionnaire' | '/strategy' | '/api/strategy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/questionnaire' | '/strategy' | '/api/strategy'
  id: '__root__' | '/' | '/questionnaire' | '/strategy' | '/api/strategy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  StrategyRoute: typeof StrategyRoute
  ApiStrategyRoute: typeof ApiStrategyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strategy': {
      id: '/api/strategy'
      path: '/api/strategy'
      fullPath: '/api/strategy'
      preLoaderRoute: typeof ApiStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  StrategyRoute: StrategyRoute,
  ApiStrategyRoute: ApiStrategyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
